# Generated by Django 2.2 on 2021-01-23 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newscategories.Category', verbose_name='Родительская Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'permissions': [('can_add_category', 'Может добавлять категории'), ('can_change_category', 'Может изменять категории'), ('can_delete_category', 'Может удалять категории'), ('can_view_category', 'Может просматривать категории')],
            },
        ),
    ]
